// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArLchWSMmy-ug7XE4Aos-WxsBgBNRGV_A',
    appId: '1:202734688492:web:392057b0665dca7b8b2dc9',
    messagingSenderId: '202734688492',
    projectId: 'arcana-tech-23b47',
    authDomain: 'arcana-tech-23b47.firebaseapp.com',
    storageBucket: 'arcana-tech-23b47.firebasestorage.app',
    measurementId: 'G-VHQ94340MD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJMSlI5qxfETXwd09MmbQIrO5-U05kRvQ',
    appId: '1:202734688492:android:c189677840b37f978b2dc9',
    messagingSenderId: '202734688492',
    projectId: 'arcana-tech-23b47',
    storageBucket: 'arcana-tech-23b47.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkiyERlrlIE_fIrNGi10MxUuCCa_ctKes',
    appId: '1:202734688492:ios:cf596f648056f4cc8b2dc9',
    messagingSenderId: '202734688492',
    projectId: 'arcana-tech-23b47',
    storageBucket: 'arcana-tech-23b47.firebasestorage.app',
    iosBundleId: 'com.example.arcanaMobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkiyERlrlIE_fIrNGi10MxUuCCa_ctKes',
    appId: '1:202734688492:ios:cf596f648056f4cc8b2dc9',
    messagingSenderId: '202734688492',
    projectId: 'arcana-tech-23b47',
    storageBucket: 'arcana-tech-23b47.firebasestorage.app',
    iosBundleId: 'com.example.arcanaMobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyArLchWSMmy-ug7XE4Aos-WxsBgBNRGV_A',
    appId: '1:202734688492:web:03c2d318fd9bc6a78b2dc9',
    messagingSenderId: '202734688492',
    projectId: 'arcana-tech-23b47',
    authDomain: 'arcana-tech-23b47.firebaseapp.com',
    storageBucket: 'arcana-tech-23b47.firebasestorage.app',
    measurementId: 'G-12KT2GFEFH',
  );
}
